# Generated by Django 4.2.30 on 2026-06-28 07:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audio_file_path', models.CharField(max_length=500)),
                ('transcribed_text', models.TextField()),
                ('duration_seconds', models.IntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_logs', to='chat.chatsession')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
