# Generated by Django 4.2.30 on 2026-06-28 11:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_certification_yogaguidance'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnifiedKnowledge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module_name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('content', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
