# Generated by Django 4.2.30 on 2026-07-02 12:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_unifiedknowledge'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentralKnowledge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='UnifiedKnowledge',
        ),
    ]
