# Generated by Django 4.2.30 on 2026-06-28 07:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_type', models.CharField(choices=[('Daily', 'Daily'), ('Weekend', 'Weekend')], max_length=50)),
                ('class_mode', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=50)),
                ('timings', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='courses.course')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedules', to='teachers.teacher')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
