# Generated by Django 4.2.30 on 2026-06-28 07:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=100)),
                ('eligibility', models.TextField()),
                ('details', models.TextField()),
                ('benefits', models.TextField()),
                ('syllabus', models.TextField()),
                ('career_opportunities', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('installment_options', models.TextField(blank=True, null=True)),
                ('discount_info', models.TextField(blank=True, null=True)),
                ('scholarships', models.TextField(blank=True, null=True)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='courses.course')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
