# Generated by Django 4.2.30 on 2026-07-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='current_topic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
