# Generated by Django 4.2.30 on 2026-07-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatsession_current_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='current_topic',
        ),
        migrations.AddField(
            model_name='chatsession',
            name='current_context',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
