# Generated by Django 4.2.30 on 2026-06-28 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
